<a href="https://colab.research.google.com/github/akhilesh-sahu12/WhiteHat-Jr_Python-AI-/blob/master/Copy_of_2021_11_01_Akhilesh_Lesson11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 11: List Comprehension

---

### Teacher-Student Tasks

In the previous lesson, we learned how to create a nested list, how to retrieve its items using the list indexing method, and how to iterate through each item in a nested list using the `for` loop.

In this lesson, we are going to learn about list comprehension. It is one of the great features of Python programming as it can create the most complicated lists through only a few lines of code.

---

#### Task 1: The `for` Loop Revision

Before we learn the list comprehension concept, let's revise the `for` loop.

Suppose you want to create a list of natural numbers starting from `1` to `10` like this:

   `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

To create this list, you will have to follow these steps:

1. Create an empty list:

   ```
   natural_numbers = []
   ```

2. Using the `for` loop, generate numbers from `1` to `10`:

   ```
   for i in range(1, 11):
   ```

   **Note:** Remember that `i` is just a variable. You can use any other variable name to iterate through the numbers generated by the `range()` function. E.g., you can use `x, y, value, item, number`, or any other letter (or word) as a variable instead of `i`.

3. Within the `for` loop, add the numbers from `1` to `10` to the empty list using the `append()` function:
   
   ```
   for i in range(1, 11):
      natural_numbers.append(i)
   ```
<img src="https://curriculum.whitehatjr.com/APT+Asset/APT+C8+images/whj-loop-apt-c8.gif" height=400/>

Let us create the Python list containing the first 10 natural numbers using the above mentioned steps:

In [ ]:
# S1.1: Create a Python list containing the first 10 natural numbers using the 'for' loop.
natural_num=[]
for i in range(1,11):
  natural_num.append(i)
natural_num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

As you can see, we have created a Python list containing the first 10 natural numbers. However, this is quite a long code to create a list. You can create the above list by writing just one line of code using the **list comprehension** method.

---

#### Task 2: The List Comprehension Method

The list comprehension method creates a Python list in a single line of code. It does not solve a new problem. It only provides a new syntax to solve an existing problem.

The core component of list comprehension is the `for` loop. To create a list using the list comprehension method, first, write the square brackets `[]`. Then inside the brackets, use the `for` loop and `in` operator to iterate through all items in the list or sequence.

**Syntax:**
```python
[expression for variable_name in list_or_sequence]
```




Let's create a list of the first `10` natural numbers using the list comprehension method:

In [ ]:
# S2.1: Create a Python list containing the first 10 natural numbers using the list comprehension method.

The list comprehension `[i for i in range(1, 11)]` should be read as "*Append `i` to the list, for every value of `i` in the range of `1` to `10`.*"

<img src="https://s3-whjr-v2-prod-bucket.whjr.online/6c323e4e-8c20-4083-92c9-ebf2c4087e7b.gif" />

<center>
<img src="https://s3-whjr-v2-prod-bucket.whjr.online/7038a02d-936d-40db-b705-a39f5db88b54.gif"/></center>

You will notice that the list comprehension eliminated the need of `append()` function.

Let us see some more examples:

**1.** **Copy list items to a new list**

 Here, we are iterating list items and appending each item to a new list. In other words, we are copying list items to a new list.

<img src="https://s3-whjr-v2-prod-bucket.whjr.online/52ed0a19-866d-42bd-b579-7d97e2e23be7.png"/>

**2. Multiplying list item with 2**

  Here, we are multiplying each list item with 2. 

<img src="https://s3-whjr-v2-prod-bucket.whjr.online/d049ed43-a3f1-4167-9d9c-3ed52a90a081.png"/>






Now, using the list comprehension method, you create a list of the square of the first `10` natural numbers:

In [ ]:
# S2.2: Create a list of the square of the first 10 natural numbers using the list comprehension method.
sq_num=[i**3 for i in range(1,11)]
sq_num

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

**Using conditional statement in list comprehension:**

You can also use a conditional statement in a list comprehension. 

**Syntax:**
```python
[expression for variable_name in list_or_sequence if condition]
```

**For e.g:**

```python
[i**3 for i in [1,2,3,4] if i>2] 
```

The above code means:
- Take item one by one from the list `[1,2,3,4]` 
- Check if that item is greater than `2`. 
    - If **yes**, take its cube and append it to the list.
    - Otherwise, ignore that item if it is less than or equal to `2`. 
    
**Output:** `[27, 64]`

---

Now first, you try to create a Python list containing even numbers from `1` and `20` using a conventional list creation approach. Here's the hint for you:

1. Create an empty list.

2. Use the `for` loop followed by a conditional statement to get even numbers.

3. Use the `append()` function to add the even numbers to the empty list.

In [ ]:
# S2.3: Create a list of even numbers from 1 to 20 using the conventional list creation method.
even_num=[]
for i in range(1,21):
  if i%2==0:
    even_num.append(i)
even_num

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In the above code:

- An empty list is created and stored in the `even_nums_list` variable. 

- The `for` loop along with the `range()` function is used to generate numbers from `1` to `20`.

- The `if i % 2 == 0` conditional statement is used to check whether the number stored in `i` is divisible by `2` or not because an even number is always divisible by `2`.

- The `append()` function is used to add the number to the `even_nums_list` which satisfies the above condition.

Now, let's generate the same list using the list comprehension method:

In [ ]:
# S2.3: Create a list of even numbers from 1 and 20 using the list comprehension method.
even1_num=[i for i in range(1,21) if i%2==0]
even1_num

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]





The list comprehension `[i for i in range(1, 21) if i % 2 == 0]` should be read as "*Add `i` to the list, for every value of `i` in the range of numbers from `1` to `20`, if `i` is divisible by 2*".

---

#### Task 3: Nested Lists Using List Comprehension

We can also create nested lists using the list comprehension method.

The creation of nested lists manually is a tedious job. We have to take care of indentation so that the list is readable in the code form. You may miss out on commas, brackets, spaces, etc. while creating a nested list. Hence, the manual nested list creation process becomes time-consuming.

Using the list comprehension method, we can create a nested list more neatly and quickly.

Suppose you have two lists and you want to join them into one nested list, then you can use the list comprehension method.

Let's assume that we want to join two lists; one containing names of the planets and another containing their corresponding diameters:

```
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto']
diameters = [4879, 12104, 12756, 6972, 142984, 120536, 51118, 49528, 2370]
```

**Note:** To save time, copy and paste the above two lists in the code cell below.

We can join these two lists into one nested list using the list comprehension method:

In [ ]:
# S3.1: Using the list comprehension method, join the four lists into one.
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto']
diameters = [4879, 12104, 12756, 6972, 142984, 120536, 51118, 49528, 2370]
planet_dia=[[planets[i],diameters[i]] for i in range(len(planets))]
planet_dia

[['Mercury', 4879],
 ['Venus', 12104],
 ['Earth', 12756],
 ['Mars', 6972],
 ['Jupiter', 142984],
 ['Saturn', 120536],
 ['Uranus', 51118],
 ['Neptune', 49528],
 ['Pluto', 2370]]

In the above code:

We calculated the number of items in the `planets` list using the  `len()` function. 




  The list comprehension `[[planets[i], diameters[i]] for i in range(n)]` should be read as '*Add the list* `[planets[i], diameters[i]]` *to the outer list, for every value of `i` in the range of numbers from `0` to `8`*.'


Now, using the same process, you combine four lists into one nested list. They are:

```
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto']
diameters = [4879, 12104, 12756, 6972, 142984, 120536, 51118, 49528, 2370]
densities = [5427, 5243, 5514, 3933, 1326, 687, 1271, 1638, 2095]
gravities = [3.7, 8.9, 9.8, 3.7, 23.1, 9.0, 8.7, 11.0, 0.7]
```

**Note:** To save time, copy and paste the above four lists in the code cell below:

In [ ]:
# S3.2: Using the list comprehension method, join the four lists into one nested list.
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto']
diameters = [4879, 12104, 12756, 6972, 142984, 120536, 51118, 49528, 2370]
densities = [5427, 5243, 5514, 3933, 1326, 687, 1271, 1638, 2095]
gravities = [3.7, 8.9, 9.8, 3.7, 23.1, 9.0, 8.7, 11.0, 0.7]
details_planet=[[planets[i],diameters[i],densities[i],gravities[i]] for i in range(len(planets))]
details_planet

[['Mercury', 4879, 5427, 3.7],
 ['Venus', 12104, 5243, 8.9],
 ['Earth', 12756, 5514, 9.8],
 ['Mars', 6972, 3933, 3.7],
 ['Jupiter', 142984, 1326, 23.1],
 ['Saturn', 120536, 687, 9.0],
 ['Uranus', 51118, 1271, 8.7],
 ['Neptune', 49528, 1638, 11.0],
 ['Pluto', 2370, 2095, 0.7]]

---

Now, let's create a nested list using the list comprehension method which has 4 identical sublists containing `0` as every item. 

Here's the desired output:

```
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
```

In [ ]:
# S3.3: Create a nested Python list using the list comprehension method, which contains 4 identical lists containing 0 as every item.
li=[0 for i in range(3)]
li

[0, 0, 0]

In [ ]:
new=[[0 for i in range(3)] for j in range(4) ]
new

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]






  It should be read as "*Add `[0, 0, 0]` to the outer list, for every `i` in the range of numbers `0` to `4`.*"

The above nested Python list can be interpreted as a two-dimensional Python list having 4 rows and 3 columns, i.e., 

```
[[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]]
```

So, in this way, we can create a two-dimensional Python list.

---
Using the same process, you try to create a new nested Python list in which each item is `1`. The nested list should contain 3 duplicate copies of a two-dimensional list containing 4 rows and 2 columns such that each item in the two-dimensional list is `1`. 

Here's the desired output:

```
[[[1, 1], [1, 1], [1, 1], [1, 1]],
 [[1, 1], [1, 1], [1, 1], [1, 1]],
 [[1, 1], [1, 1], [1, 1], [1, 1]]]
```
The above nested Python list can also be interpreted as a three-dimensional Python list having 3 blocks such that each block has 4 rows and 2 columns:

```
[[[1, 1], 
  [1, 1], 
  [1, 1], 
  [1, 1]],

 [[1, 1], 
  [1, 1], 
  [1, 1], 
  [1, 1]],

 [[1, 1], 
  [1, 1], 
  [1, 1], 
  [1, 1]]]
```




For this, you need 3 `for` loops in the list comprehension syntax:
1. An inner `for` loop for 2 columns $\Rightarrow$ `for i in range(2)`.
2. An inner `for` loop for 4 rows $\Rightarrow$ `for j in range(4)`
3. Outer `for` loop for 3 blocks or 3 copies $\Rightarrow$ `for k in range(3)`

In [ ]:
# S3.4: Create a new nested Python list in which each item is 1 using the list comprehension method. 
# Store it in the 'ones' variable.
# It should have 3 duplicate copies of the '[[1, 1], [1, 1], [1, 1], [1, 1]]'.
inner=[1 for i in range(2)]
outer=[[1 for i in range(2)] for j in range(4)]
most_outer=[[[1 for i in range(2)] for j in range(4)] for k in range(3) ]
most_outer

[[[1, 1], [1, 1], [1, 1], [1, 1]],
 [[1, 1], [1, 1], [1, 1], [1, 1]],
 [[1, 1], [1, 1], [1, 1], [1, 1]]]

In the above code:

- The `[1 for i in range(2)]` list comprehension creates a list containing two items such that each item is `1`, i.e., `[1, 1]`.

- The `[[1 for i in range(2)] for j in range(4)]` list comprehension creates four duplicate copies of the `[1, 1]` list, i.e., 
  
  `[[1, 1], [1, 1], [1, 1], [1, 1]]`

- The outermost list comprehension creates three duplicate copies of the `[[[1, 1], [1, 1], [1, 1], [1, 1]]` list, i.e., 

  ```
  [[[1, 1], [1, 1], [1, 1], [1, 1]],
  [[1, 1], [1, 1], [1, 1], [1, 1]],
  [[1, 1], [1, 1], [1, 1], [1, 1]]]
  ```


---
Now, let's create the following two-dimensional list using the list comprehension method:

```
 [[11, 12],
  [21, 22]]
```

In the above nested list:

- The digits both at the tens and units places go from `1` to `2`. 

- The digit at tens place in the first row is always `1`. 

- The digit at tens place in the second row is always `2`. 

So, we need to write a logic to create the above nested list keeping these things in mind.

In [ ]:
# S3.5: Create the '[[11, 12], [21, 22]]' using the list comprehension method.
lis=[[(i*10+j) for j in range(1,3) ] for i in range(1,3)]
lis

[[11, 12], [21, 22]]

In the above code:

- For `i = 1`, the list comprehension `[(10 * i + j) for j in range(1, 3)]` creates the following list:

  `[(10 * 1 + 1), (10 * 1 + 2)]`, i.e. `[11, 12]`

  Because for `i = 1`, the value of `j` goes from `1` to `2`. Thus, the inner `for` loop gives two numbers: 

    - For `j = 1`, we get `10 * 1 + 1 = 11` 
    
    - For `j = 2`, we get `10 * 1 + 2 = 12`

- For `i = 2`, the list comprehension `[(10 * i + j) for j in range(1, 3)]` creates the following list:

  `[(10 * 2 + 1), (10 * 2 + 2)]`, i.e. `[21, 22]`

  Because for `i = 2`, the value of `j` goes from `1` to `2`. Thus, the inner `for` loop gives two numbers: 
    
    - For `j = 1`, we get `10 * 2 + 1 = 21`
    
    - For `j = 2`, we get `10 * 2 + 2 = 22`

We will stop here. Thus, in this class, we learned list comprehension which helps us in creating different types of Python lists using lesser code. In the next class, we will learn about NumPy arrays.

---